### PR TITLE
add config option for using dvd episode order

### PR DESCRIPTION
**Pull request by hoax92**

### CODE REVIEW

**Comment by dbr** [comment]
Thanks! I think this feature has been requested a couple of times

A few hopefully minor things:

I think it would be tidier having a single argument like `--order aired` or `--order dvd` instead of separate arg for each (because there's no case where you'd want to specify both)

Similarly, should store the option in the config as a "aired"/"dvd" string instead of true/false (as it's not immediately obvious what dvdorder:false does)

Oh, and could you add a simple test case for this? Just duplicate one of the functions in `test_functional.py`, set the new config option and change the expected file names

**Comment by hoax92** [comment]
hi,

thanks for your review!
changes done.

BR

**Comment by dbr** [comment]
Looks good - merged, thanks!

**Comment by hoax92** [comment]
thank you!

**Comment by dbr** [comment]
Belatedly released as tvnamer 2.4 - thanks again!

**Pull request merged**
