### PR TITLE
move config file to .config for a cleaner home directory

### PR DESCRIPTION
**Pull request by Monirzadeh**

### CODE REVIEW

**Comment by Monirzadeh** [comment]
as i mention here #166

**Comment by dbr** [comment]
Thanks for the PR!

I'm definitely in favour of using the `~/.config/` folder, but this needs a fallback to still load `~/.tvnamer.conf` for backwards compatibility with existing configs.

The `~/.config/...` one would take preference, and the presence of the old config should output a warning. I imagine the logic would be:

1. Check for `~/.config/tvnamer/tvnamer.json` - load this if present
2. If not present, check for `~/.tvnamer.json` - load this
3. If `~/.tvnamer.json` is present, output warning informing user of new location (this should happen regardless if `~/.config/...` file exists to avoid confusion)

I'm happy to make these changes for the next release if you don't have time!

**Comment by Monirzadeh** [comment]
i don't write python code for a long time but i can try
i don't read  source code for completely but it should be https://github.com/dbr/tvnamer/blob/f3af5e17cb9ef77af0470abe3a2e3352c54e676b/tvnamer/main.py#L388 until line 432

**Comment by dbr** [comment]
Looks good to me! I think a single message if the old config file exists is fine - there's a minor typo in the message but easier for me to tweak that after merging.

Thanks! I think this is the last improvement I wanted to sort out before releasing v2.6, shall hopefully get to that in the next few days

**Pull request merged**
